config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'project', to: 'pages#project', as: :project
  get 'contact', to: 'pages#contact', as: :contact
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arthur Picard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Roboto:wght@100;400&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row m-5">
  <div class="column">
    <%= link_to image_tag("me8")%>
  </div>
  <div class="column about">
    <h1 style="text-align: center">About me 👨🏼‍💻</h1>
    <h3>Connect with me:</h3>
    <p style="text-align: center">
    <a href="https://linkedin.com/in/arpicard" target="blank"><img src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="arpicard" height="30" width="40" /></a>
    </p>

    <h3>Languages and Tools:</h3>
    <p>
      <a href="https://getbootstrap.com" target="_blank" rel="noreferrer">
        <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg" alt="bootstrap" width="40" height="40"/>
      </a>
      <a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer">
        <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg" alt="css3" width="40" height="40"/>
      </a>
      <a href="https://www.figma.com/" target="_blank" rel="noreferrer">
        <img src="https://www.vectorlogo.zone/logos/figma/figma-icon.svg" alt="figma" width="40" height="40"/>
      </a>
      <a href="https://git-scm.com/" target="_blank" rel="noreferrer">
        <img src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg" alt="git" width="40" height="40"/>
      </a>
      <a href="https://heroku.com" target="_blank" rel="noreferrer">
        <img src="https://www.vectorlogo.zone/logos/heroku/heroku-icon.svg" alt="heroku" width="40" height="40"/>
      </a>
      <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer">
        <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40"/>
      </a>
      <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank" rel="noreferrer">
        <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" alt="javascript" width="40" height="40"/>
      </a>
      <a href="https://www.photoshop.com/en" target="_blank" rel="noreferrer">
        <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/photoshop/photoshop-line.svg" alt="photoshop" width="40" height="40"/>
      </a>
      <a href="https://rubyonrails.org" target="_blank" rel="noreferrer">
        <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/rails/rails-original-wordmark.svg" alt="rails" width="40" height="40"/>
      </a>
      <a href="https://reactjs.org/" target="_blank" rel="noreferrer">
        <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg" alt="react" width="40" height="40"/>
      </a>
      <a href="https://www.ruby-lang.org/en/" target="_blank" rel="noreferrer">
        <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/ruby/ruby-original.svg" alt="ruby" width="40" height="40"/>
      </a>
      <a href="https://sass-lang.com" target="_blank" rel="noreferrer">
        <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg" alt="sass" width="40" height="40"/>
      </a>
    </p>
  </div>
</div>

app/views/pages/contact.html.erb
<%= render 'shared/contact' %>

app/views/pages/home.html.erb
<div class="banner m-3" style="background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
  <div class="d-flex">
    <div class="container ml-5">
      <h2>Hey there 👋🏼 </h2>
      <h1>I'm <span class="myname" >Arthur</span> !</h1>
      <p>A passionate Full Stack Developer</p>
      <a class="btn btn-flat m-5" href="project">Check my Portfolio</a>
    </div>
    <div class="container ml-5 pl-5">
      <h1><%= link_to image_tag('arthur-emoji.png') %></h1>
    </div>
  </div>
</div>
<div class="hero-section m-5 p-5">
  <h2>Learn more about me</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vel molestie dui, vel commodo metus. Curabitur vitae quam augue. Maecenas viverra arcu venenatis ligula venenatis cursus sed vel augue. Nulla orci felis, tempor ac laoreet tempor, egestas vel augue. Nulla maximus lorem sed sem sollicitudin feugiat. Morbi consectetur interdum massa, ut interdum augue suscipit sollicitudin. Curabitur mattis felis enim, sit amet posuere diam cursus at. Duis porta metus eget felis rutrum tempor. Cras convallis condimentum enim nec placerat. Mauris quam odio, iaculis eget ultrices pharetra, suscipit eu nibh. Quisque lorem est, imperdiet vel neque vitae, tristique malesuada neque. Fusce suscipit quam et lacus scelerisque tempus. Sed eleifend laoreet nisl, ac feugiat nunc hendrerit sit amet. Vivamus pellentesque tortor et mi tempus, at lobortis neque tincidunt. Donec pulvinar pretium lorem ut porttitor. Quisque vitae felis eu metus maximus elementum et nec elit. Phasellus fringilla nunc finibus lectus hendrerit scelerisque. Nam id luctus risus.</p>
  <br>
</div>
<h2 class="m-5">Wanna see more about my projects ?</h2>
<div>
  <%= render 'shared/card-overview' %>
</div>
<div>
  <%= render 'shared/card-overview' %>
</div>

app/views/pages/project.html.erb
<h2>Here are some of my personal web projects</h2>
<%= render 'shared/card-trip' %>

app/views/shared/_card-overview.html.erb
<div class="d-flex m-2">
  <div class="card-trip m-3">
    <%= link_to image_tag("cryptons-homepage.png"), "http://www.cryptons.me", target: "_blank"%>
    <div class="card-trip-infos">
      <div>
        <h2><%= link_to "Cryptons", "http://www.cryptons.me", target: "_blank" %></h2>
        <p>This web App is a Real time Cryptocurrency portfolio tracker</p>
      </div>
    </div>
  </div>
  <div class="card-trip m-3">
    <%= link_to image_tag("origin-show.png"), "http://www.beerorigins.herokuapp.com", target: "_blank" %>
    <div class="card-trip-infos">
      <div>
        <h2><%= link_to "Beer Origins", "http://www.beerorigins.herokuapp.com", target: "_blank" %></h2>
        <p>This web App is a clone of Airbnb about Craft Beer Factory</p>
      </div>
    </div>
  </div>
  <div class="card-trip m-3">
    <%= link_to image_tag("movie-db.png"), "#", target: "_blank" %>
    <div class="card-trip-infos">
      <div>
        <h2><%= link_to "Movie DB", "#", target: "_blank" %></h2>
        <p>This web App is a Movie database where you will be able to get more information about any movies.</p>
      </div>
    </div>
  </div>
  <div class="card-trip m-3">
    <%= link_to image_tag("movie-db.png"), "#", target: "_blank" %>
    <div class="card-trip-infos">
      <div>
        <h2><%= link_to "Movie DB", "#", target: "_blank" %></h2>
        <p>This web App is a Movie database where you will be able to get more information about any movies.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card-trip.html.erb
<%# PROJECT #1 - CRYPTONS %>
<div class="card-product mt-5">
  <%= link_to image_tag("cryptons-homepage.png"), "http://www.cryptons.me", target: "_blank"%>
  <div class="card-product-infos">
    <h2><%= link_to "Cryptons", "http://www.cryptons.me", target: "_blank" %></h2>
    <p>This web App is a Real time Cryptocurrency portfolio tracker Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aliquam consequatur vero eos reiciendis pariatur temporibus perferendis, nemo mollitia autem beatae porro dolorum sit incidunt fugiat ad esse tempore explicabo voluptatibus!<strong></strong></p>
  </div>
</div>

<%# PROJECT #2 - BEER ORIGINS %>
<div class="card-product-right mt-5">
  <div class="card-product-infos-right">
    <h2><%= link_to "Beer Origins", "http://www.beerorigins.herokuapp.com", target: "_blank" %></h2>
    <p>This web App is a AirBnb clone of <strong>Craft Beer factory</strong>. This web App is a Real time Cryptocurrency portfolio tracker Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aliquam consequatur vero eos reiciendis pariatur temporibus perferendis, nemo mollitia autem beatae porro dolorum sit incidunt fugiat ad esse tempore explicabo voluptatibus!</p>
  </div>
    <%= link_to image_tag("origin-show.png"), "http://www.beerorigins.herokuapp.com", target: "_blank" %>
</div>

<%# PROJECT #3 - MOVIE DB %>
<div class="card-product mt-5">
  <%= link_to image_tag("movie-db.png"), "", target: "_blank"%>
  <div class="card-product-infos">
    <h2><%= link_to "Movie DB", "", target: "_blank" %></h2>
    <p>This web App is a Real time Cryptocurrency portfolio tracker Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aliquam consequatur vero eos reiciendis pariatur temporibus perferendis, nemo mollitia autem beatae porro dolorum sit incidunt fugiat ad esse tempore explicabo voluptatibus!<strong></strong></p>
  </div>
</div>

app/views/shared/_contact.html.erb
<div class="contact">
  <div class="container">
    <div style="text-align:center">
      <h2>Contact Me</h2>
      <p>Swing by for a cup of coffee, or leave me a message:</p>
    </div>
    <div class="row">
      <div class="column">
        <%= link_to image_tag('arthur-heart.png') %>
      </div>
      <div class="column">
        <form action="/action_page.php">
          <label for="fname">First Name</label>
          <input type="text" id="fname" name="firstname" placeholder="Your name..">
          <label for="lname">Last Name</label>
          <input type="text" id="lname" name="lastname" placeholder="Your last name..">
          <label for="subject">Subject</label>
          <textarea id="subject" name="subject" placeholder="Write something.." style="height:170px"></textarea>
          <input type="submit" value="Submit">
        </form>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer mt-5 mb-0">
  <div class="footer-navbar m-0">
    <ol class="footer-list m-0">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Projects", project_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ol>
  </div>
  <div class="d-flex justify-content-center">
    <p>Made by <%= image_tag "arthur_picard.png" %> with ❤️</p>
  </div>
  <div class="footer-links">
    <a href="https://github.com/Arthurwzy27"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/in/arpicard/"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "arthur_picard.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Projects", project_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= simple_form_for :search, url: root_path, method: :get do |f| %>
          <div class="search-form-control form-group">
            <input class="form-control string required" type="text" name="search[query]" id="search_query" />
            <button name="button" type="submit" class="btn btn-flat">
              <i class="fas fa-search"></i>
            </button>
          </div>
        <% end %>
      </li>





    </ul>
  </div>
</div>